version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies..."
      - yum install -y jq

  pre_build:
    commands:
      - echo "Fetching database credentials from Secrets Manager..."
      - |
        SECRET_VALUE=$(aws secretsmanager get-secret-value \
          --secret-id $DB_SECRET_ARN \
          --query SecretString \
          --output text)

        export DB_HOST=$(echo $SECRET_VALUE | jq -r .host)
        export DB_PORT=$(echo $SECRET_VALUE | jq -r .port)
        export DB_NAME=$(echo $SECRET_VALUE | jq -r .dbname)
        export DB_USER=$(echo $SECRET_VALUE | jq -r .username)
        export DB_PASS=$(echo $SECRET_VALUE | jq -r .password)

        echo "Database host: $DB_HOST"
        echo "Database port: $DB_PORT"
        echo "Database name: $DB_NAME"
        echo "Database user: $DB_USER"

  build:
    commands:
      - echo "Running Liquibase migration..."
      - |
        export DB_URL="$DB_HOST:$DB_PORT/$DB_NAME"
        ./gradlew update --no-daemon
      - echo "Migration completed successfully"

  post_build:
    commands:
      - echo "Migration finished at $(date)"
